enable EventBasedListProbe to hande (value,time) and (time,value) metric descs.
PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-Monitoring pull request #13
Opened 2023-08-24 16:33 UTC by stiesssh

There are apparently multiple MetricSetDescriptions that use  (value, time) instead of  (time, value).
Among others the Number Of Resources, for which we need a monitor (c.f. PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-PCM-Core#41)

## Current behaviour
EventBasedListProbe only handles (time,value)  pairs correctly, all other throw exceptions. 

## New behaviour
EventBasedListProbe can handle bothe  (time,value) and  (value, time) pairs without  exceptions.

2023-08-30 11:43 UTC, kjuli approved these changes
I tested it and it worked. I would suggest to make the fields private though, but this is a minor issue

2023-08-30 11:43 UTC, kjuli commented on org.palladiosimulator.analyzer.slingshot.monitor/src/org/palladiosimulator/analyzer/slingshot/monitor/probes/EventBasedListProbe.java
> +	Function<DESEvent, MeasuringValue> secondvalue;
Do other classes in the same package need these fields? I think they should be made private just in case

2023-08-30 12:39 UTC, kjuli requested changes
WAIT: I get an error in `ResourceDemandRequestedProbe`: **The method `getTime(DESEvent)` of type `ResourceDemandRequestedProbe` must override or implement a supertype method**.

As I see it, it's because the method `getTime` in the super class `EventBasedListProbe` is private.

2023-08-31 06:25 UTC, stiesssh commented
> WAIT: I get an error in `ResourceDemandRequestedProbe`: **The method `getTime(DESEvent)` of type `ResourceDemandRequestedProbe` must override or implement a supertype method**.
> 
> As I see it, it's because the method `getTime` in the super class `EventBasedListProbe` is private.

ahhh, my bad. 
take this : PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-PCM-Core#42

2023-09-02 17:08 UTC, kjuli approved these changes
It now compiles and seems to work

2023-09-04 06:59 UTC, merged